import { Country } from './country';

export var COUNTRIES: Country[] =[
    { "code": "null", "id": "null", "title": "Select Country ...", "name": "Select Country ..." },
    { "code": "ad", "id": "ad", "title": "Andorra", "name": "Andorra" },
    { "code": "ae", "id": "ae", "title": "United Arab Emirates", "name": "United Arab Emirates" },
    { "code": "af", "id": "af", "title": "Afghanistan", "name": "Afghanistan" },
    { "code": "ag", "id": "ag", "title": "Antigua and Barbuda", "name": "Antigua and Barbuda" },
    { "code": "ai", "id": "ai", "title": "Anguilla", "name": "Anguilla" },
    { "code": "al", "id": "al", "title": "Albania", "name": "Albania" },
    { "code": "am", "id": "am", "title": "Armenia", "name": "Armenia" },
    { "code": "an", "id": "an", "title": "Netherlands Antilles", "name": "Netherlands Antilles" },
    { "code": "ao", "id": "ao", "title": "Angola", "name": "Angola" },
    { "code": "aq", "id": "aq", "title": "Antarctica", "name": "Antarctica" },
    { "code": "ar", "id": "ar", "title": "Argentina", "name": "Argentina" },
    { "code": "as", "id": "as", "title": "American Samoa", "name": "American Samoa" },
    { "code": "at", "id": "at", "title": "Austria", "name": "Austria" },
    { "code": "au", "id": "au", "title": "Australia", "name": "Australia" },
    { "code": "aw", "id": "aw", "title": "Aruba", "name": "Aruba" },
    { "code": "ax", "id": "ax", "title": "Aland Islands", "name": "Aland Islands" },
    { "code": "az", "id": "az", "title": "Azerbaijan", "name": "Azerbaijan" },
    { "code": "ba", "id": "ba", "title": "Bosnia and Herzegovina", "name": "Bosnia and Herzegovina" },
    { "code": "bb", "id": "bb", "title": "Barbados", "name": "Barbados" },
    { "code": "bd", "id": "bd", "title": "Bangladesh", "name": "Bangladesh" },
    { "code": "be", "id": "be", "title": "Belgium", "name": "Belgium" },
    { "code": "bf", "id": "bf", "title": "Burkina Faso", "name": "Burkina Faso" },
    { "code": "bg", "id": "bg", "title": "Bulgaria", "name": "Bulgaria" },
    { "code": "bh", "id": "bh", "title": "Bahrain", "name": "Bahrain" },
    { "code": "bi", "id": "bi", "title": "Burundi", "name": "Burundi" },
    { "code": "bj", "id": "bj", "title": "Benin", "name": "Benin" },
    { "code": "bm", "id": "bm", "title": "Bermuda", "name": "Bermuda" },
    { "code": "bn", "id": "bn", "title": "Brunei Darussalam", "name": "Brunei Darussalam" },
    { "code": "bo", "id": "bo", "title": "Bolivia", "name": "Bolivia" },
    { "code": "br", "id": "br", "title": "Brazil", "name": "Brazil" },
    { "code": "bs", "id": "bs", "title": "Bahamas", "name": "Bahamas" },
    { "code": "bt", "id": "bt", "title": "Bhutan", "name": "Bhutan" },
    { "code": "bv", "id": "bv", "title": "Bouvet Island", "name": "Bouvet Island" },
    { "code": "bw", "id": "bw", "title": "Botswana", "name": "Botswana" },
    { "code": "by", "id": "by", "title": "Belarus", "name": "Belarus" },
    { "code": "bz", "id": "bz", "title": "Belize", "name": "Belize" },
    { "code": "ca", "id": "ca", "title": "Canada", "name": "Canada" },
    { "code": "cc", "id": "cc", "title": "Cocos (Keeling) Islands", "name": "Cocos (Keeling) Islands" },
    { "code": "cd", "id": "cd", "title": "Democratic Republic of the Congo", "name": "Democratic Republic of the Congo" },
    { "code": "cf", "id": "cf", "title": "Central African Republic", "name": "Central African Republic" },
    { "code": "cg", "id": "cg", "title": "Congo", "name": "Congo" },
    { "code": "ch", "id": "ch", "title": "Switzerland", "name": "Switzerland" },
    { "code": "ci", "id": "ci", "title": "Cote D'Ivoire (Ivory Coast)", "name": "Cote D'Ivoire (Ivory Coast)" },
    { "code": "ck", "id": "ck", "title": "Cook Islands", "name": "Cook Islands" },
    { "code": "cl", "id": "cl", "title": "Chile", "name": "Chile" },
    { "code": "cm", "id": "cm", "title": "Cameroon", "name": "Cameroon" },
    { "code": "cn", "id": "cn", "title": "China", "name": "China" },
    { "code": "co", "id": "co", "title": "Colombia", "name": "Colombia" },
    { "code": "cr", "id": "cr", "title": "Costa Rica", "name": "Costa Rica" },
    { "code": "cs", "id": "cs", "title": "Serbia and Montenegro", "name": "Serbia and Montenegro" },
    { "code": "cu", "id": "cu", "title": "Cuba", "name": "Cuba" },
    { "code": "cv", "id": "cv", "title": "Cape Verde", "name": "Cape Verde" },
    { "code": "cx", "id": "cx", "title": "Christmas Island", "name": "Christmas Island" },
    { "code": "cy", "id": "cy", "title": "Cyprus", "name": "Cyprus" },
    { "code": "cz", "id": "cz", "title": "Czech Republic", "name": "Czech Republic" },
    { "code": "de", "id": "de", "title": "Germany", "name": "Germany" },
    { "code": "dj", "id": "dj", "title": "Djibouti", "name": "Djibouti" },
    { "code": "dk", "id": "dk", "title": "Denmark", "name": "Denmark" },
    { "code": "dm", "id": "dm", "title": "Dominica", "name": "Dominica" },
    { "code": "do", "id": "do", "title": "Dominican Republic", "name": "Dominican Republic" },
    { "code": "dz", "id": "dz", "title": "Algeria", "name": "Algeria" },
    { "code": "ec", "id": "ec", "title": "Ecuador", "name": "Ecuador" },
    { "code": "ee", "id": "ee", "title": "Estonia", "name": "Estonia" },
    { "code": "eg", "id": "eg", "title": "Egypt", "name": "Egypt" },
    { "code": "eh", "id": "eh", "title": "Western Sahara", "name": "Western Sahara" },
    { "code": "er", "id": "er", "title": "Eritrea", "name": "Eritrea" },
    { "code": "es", "id": "es", "title": "Spain", "name": "Spain" },
    { "code": "et", "id": "et", "title": "Ethiopia", "name": "Ethiopia" },
    { "code": "fi", "id": "fi", "title": "Finland", "name": "Finland" },
    { "code": "fj", "id": "fj", "title": "Fiji", "name": "Fiji" },
    { "code": "fk", "id": "fk", "title": "Falkland Islands (Malvinas)", "name": "Falkland Islands (Malvinas)" },
    { "code": "fm", "id": "fm", "title": "Federated States of Micronesia", "name": "Federated States of Micronesia" },
    { "code": "fo", "id": "fo", "title": "Faroe Islands", "name": "Faroe Islands" },
    { "code": "fr", "id": "fr", "title": "France", "name": "France" },
    { "code": "fx", "id": "fx", "title": "France, Metropolitan", "name": "France, Metropolitan" },
    { "code": "ga", "id": "ga", "title": "Gabon", "name": "Gabon" },
    { "code": "gb", "id": "gb", "title": "Great Britain (UK)", "name": "Great Britain (UK)" },
    { "code": "gd", "id": "gd", "title": "Grenada", "name": "Grenada" },
    { "code": "ge", "id": "ge", "title": "Georgia", "name": "Georgia" },
    { "code": "gf", "id": "gf", "title": "French Guiana", "name": "French Guiana" },
    { "code": "gh", "id": "gh", "title": "Ghana", "name": "Ghana" },
    { "code": "gi", "id": "gi", "title": "Gibraltar", "name": "Gibraltar" },
    { "code": "gl", "id": "gl", "title": "Greenland", "name": "Greenland" },
    { "code": "gm", "id": "gm", "title": "Gambia", "name": "Gambia" },
    { "code": "gn", "id": "gn", "title": "Guinea", "name": "Guinea" },
    { "code": "gp", "id": "gp", "title": "Guadeloupe", "name": "Guadeloupe" },
    { "code": "gq", "id": "gq", "title": "Equatorial Guinea", "name": "Equatorial Guinea" },
    { "code": "gr", "id": "gr", "title": "Greece", "name": "Greece" },
    { "code": "gs", "id": "gs", "title": "S. Georgia and S. Sandwich Islands", "name": "S. Georgia and S. Sandwich Islands" },
    { "code": "gt", "id": "gt", "title": "Guatemala", "name": "Guatemala" },
    { "code": "gu", "id": "gu", "title": "Guam", "name": "Guam" },
    { "code": "gw", "id": "gw", "title": "Guinea-Bissau", "name": "Guinea-Bissau" },
    { "code": "gy", "id": "gy", "title": "Guyana", "name": "Guyana" },
    { "code": "hk", "id": "hk", "title": "Hong Kong", "name": "Hong Kong" },
    { "code": "hm", "id": "hm", "title": "Heard Island and McDonald Islands", "name": "Heard Island and McDonald Islands" },
    { "code": "hn", "id": "hn", "title": "Honduras", "name": "Honduras" },
    { "code": "hr", "id": "hr", "title": "Croatia (Hrvatska)", "name": "Croatia (Hrvatska)" },
    { "code": "ht", "id": "ht", "title": "Haiti", "name": "Haiti" },
    { "code": "hu", "id": "hu", "title": "Hungary", "name": "Hungary" },
    { "code": "id", "id": "id", "title": "Indonesia", "name": "Indonesia" },
    { "code": "ie", "id": "ie", "title": "Ireland", "name": "Ireland" },
    { "code": "il", "id": "il", "title": "Israel", "name": "Israel" },
    { "code": "in", "id": "in", "title": "India", "name": "India" },
    { "code": "io", "id": "io", "title": "British Indian Ocean Territory", "name": "British Indian Ocean Territory" },
    { "code": "iq", "id": "iq", "title": "Iraq", "name": "Iraq" },
    { "code": "ir", "id": "ir", "title": "Iran", "name": "Iran" },
    { "code": "is", "id": "is", "title": "Iceland", "name": "Iceland" },
    { "code": "it", "id": "it", "title": "Italy", "name": "Italy" },
    { "code": "jm", "id": "jm", "title": "Jamaica", "name": "Jamaica" },
    { "code": "jo", "id": "jo", "title": "Jordan", "name": "Jordan" },
    { "code": "jp", "id": "jp", "title": "Japan", "name": "Japan" },
    { "code": "ke", "id": "ke", "title": "Kenya", "name": "Kenya" },
    { "code": "kg", "id": "kg", "title": "Kyrgyzstan", "name": "Kyrgyzstan" },
    { "code": "kh", "id": "kh", "title": "Cambodia", "name": "Cambodia" },
    { "code": "ki", "id": "ki", "title": "Kiribati", "name": "Kiribati" },
    { "code": "km", "id": "km", "title": "Comoros", "name": "Comoros" },
    { "code": "kn", "id": "kn", "title": "Saint Kitts and Nevis", "name": "Saint Kitts and Nevis" },
    { "code": "kp", "id": "kp", "title": "Korea (North)", "name": "Korea (North)" },
    { "code": "kr", "id": "kr", "title": "Korea (South)", "name": "Korea (South)" },
    { "code": "kw", "id": "kw", "title": "Kuwait", "name": "Kuwait" },
    { "code": "ky", "id": "ky", "title": "Cayman Islands", "name": "Cayman Islands" },
    { "code": "kz", "id": "kz", "title": "Kazakhstan", "name": "Kazakhstan" },
    { "code": "la", "id": "la", "title": "Laos", "name": "Laos" },
    { "code": "lb", "id": "lb", "title": "Lebanon", "name": "Lebanon" },
    { "code": "lc", "id": "lc", "title": "Saint Lucia", "name": "Saint Lucia" },
    { "code": "li", "id": "li", "title": "Liechtenstein", "name": "Liechtenstein" },
    { "code": "lk", "id": "lk", "title": "Sri Lanka", "name": "Sri Lanka" },
    { "code": "lr", "id": "lr", "title": "Liberia", "name": "Liberia" },
    { "code": "ls", "id": "ls", "title": "Lesotho", "name": "Lesotho" },
    { "code": "lt", "id": "lt", "title": "Lithuania", "name": "Lithuania" },
    { "code": "lu", "id": "lu", "title": "Luxembourg", "name": "Luxembourg" },
    { "code": "lv", "id": "lv", "title": "Latvia", "name": "Latvia" },
    { "code": "ly", "id": "ly", "title": "Libya", "name": "Libya" },
    { "code": "ma", "id": "ma", "title": "Morocco", "name": "Morocco" },
    { "code": "mc", "id": "mc", "title": "Monaco", "name": "Monaco" },
    { "code": "md", "id": "md", "title": "Moldova", "name": "Moldova" },
    { "code": "mg", "id": "mg", "title": "Madagascar", "name": "Madagascar" },
    { "code": "mh", "id": "mh", "title": "Marshall Islands", "name": "Marshall Islands" },
    { "code": "mk", "id": "mk", "title": "Macedonia", "name": "Macedonia" },
    { "code": "ml", "id": "ml", "title": "Mali", "name": "Mali" },
    { "code": "mm", "id": "mm", "title": "Myanmar", "name": "Myanmar" },
    { "code": "mn", "id": "mn", "title": "Mongolia", "name": "Mongolia" },
    { "code": "mo", "id": "mo", "title": "Macao", "name": "Macao" },
    { "code": "mp", "id": "mp", "title": "Northern Mariana Islands", "name": "Northern Mariana Islands" },
    { "code": "mq", "id": "mq", "title": "Martinique", "name": "Martinique" },
    { "code": "mr", "id": "mr", "title": "Mauritania", "name": "Mauritania" },
    { "code": "ms", "id": "ms", "title": "Montserrat", "name": "Montserrat" },
    { "code": "mt", "id": "mt", "title": "Malta", "name": "Malta" },
    { "code": "mu", "id": "mu", "title": "Mauritius", "name": "Mauritius" },
    { "code": "mv", "id": "mv", "title": "Maldives", "name": "Maldives" },
    { "code": "mw", "id": "mw", "title": "Malawi", "name": "Malawi" },
    { "code": "mx", "id": "mx", "title": "Mexico", "name": "Mexico" },
    { "code": "my", "id": "my", "title": "Malaysia", "name": "Malaysia" },
    { "code": "mz", "id": "mz", "title": "Mozambique", "name": "Mozambique" },
    { "code": "na", "id": "na", "title": "Namibia", "name": "Namibia" },
    { "code": "nc", "id": "nc", "title": "New Caledonia", "name": "New Caledonia" },
    { "code": "ne", "id": "ne", "title": "Niger", "name": "Niger" },
    { "code": "nf", "id": "nf", "title": "Norfolk Island", "name": "Norfolk Island" },
    { "code": "ng", "id": "ng", "title": "Nigeria", "name": "Nigeria" },
    { "code": "ni", "id": "ni", "title": "Nicaragua", "name": "Nicaragua" },
    { "code": "nl", "id": "nl", "title": "Netherlands", "name": "Netherlands" },
    { "code": "no", "id": "no", "title": "Norway", "name": "Norway" },
    { "code": "np", "id": "np", "title": "Nepal", "name": "Nepal" },
    { "code": "nr", "id": "nr", "title": "Nauru", "name": "Nauru" },
    { "code": "nu", "id": "nu", "title": "Niue", "name": "Niue" },
    { "code": "nz", "id": "nz", "title": "New Zealand (Aotearoa)", "name": "New Zealand (Aotearoa)" },
    { "code": "om", "id": "om", "title": "Oman", "name": "Oman" },
    { "code": "pa", "id": "pa", "title": "Panama", "name": "Panama" },
    { "code": "pe", "id": "pe", "title": "Peru", "name": "Peru" },
    { "code": "pf", "id": "pf", "title": "French Polynesia", "name": "French Polynesia" },
    { "code": "pg", "id": "pg", "title": "Papua New Guinea", "name": "Papua New Guinea" },
    { "code": "ph", "id": "ph", "title": "Philippines", "name": "Philippines" },
    { "code": "pk", "id": "pk", "title": "Pakistan", "name": "Pakistan" },
    { "code": "pl", "id": "pl", "title": "Poland", "name": "Poland" },
    { "code": "pm", "id": "pm", "title": "Saint Pierre and Miquelon", "name": "Saint Pierre and Miquelon" },
    { "code": "pn", "id": "pn", "title": "Pitcairn", "name": "Pitcairn" },
    { "code": "pr", "id": "pr", "title": "Puerto Rico", "name": "Puerto Rico" },
    { "code": "ps", "id": "ps", "title": "Palestinian Territory", "name": "Palestinian Territory" },
    { "code": "pt", "id": "pt", "title": "Portugal", "name": "Portugal" },
    { "code": "pw", "id": "pw", "title": "Palau", "name": "Palau" },
    { "code": "py", "id": "py", "title": "Paraguay", "name": "Paraguay" },
    { "code": "qa", "id": "qa", "title": "Qatar", "name": "Qatar" },
    { "code": "re", "id": "re", "title": "Reunion", "name": "Reunion" },
    { "code": "ro", "id": "ro", "title": "Romania", "name": "Romania" },
    { "code": "ru", "id": "ru", "title": "Russian Federation", "name": "Russian Federation" },
    { "code": "rw", "id": "rw", "title": "Rwanda", "name": "Rwanda" },
    { "code": "sa", "id": "sa", "title": "Saudi Arabia", "name": "Saudi Arabia" },
    { "code": "sb", "id": "sb", "title": "Solomon Islands", "name": "Solomon Islands" },
    { "code": "sc", "id": "sc", "title": "Seychelles", "name": "Seychelles" },
    { "code": "sd", "id": "sd", "title": "Sudan", "name": "Sudan" },
    { "code": "se", "id": "se", "title": "Sweden", "name": "Sweden" },
    { "code": "sg", "id": "sg", "title": "Singapore", "name": "Singapore" },
    { "code": "sh", "id": "sh", "title": "Saint Helena", "name": "Saint Helena" },
    { "code": "si", "id": "si", "title": "Slovenia", "name": "Slovenia" },
    { "code": "sj", "id": "sj", "title": "Svalbard and Jan Mayen", "name": "Svalbard and Jan Mayen" },
    { "code": "sk", "id": "sk", "title": "Slovakia", "name": "Slovakia" },
    { "code": "sl", "id": "sl", "title": "Sierra Leone", "name": "Sierra Leone" },
    { "code": "sm", "id": "sm", "title": "San Marino", "name": "San Marino" },
    { "code": "sn", "id": "sn", "title": "Senegal", "name": "Senegal" },
    { "code": "so", "id": "so", "title": "Somalia", "name": "Somalia" },
    { "code": "sr", "id": "sr", "title": "Suriname", "name": "Suriname" },
    { "code": "st", "id": "st", "title": "Sao Tome and Principe", "name": "Sao Tome and Principe" },
    { "code": "su", "id": "su", "title": "USSR (former)", "name": "USSR (former)" },
    { "code": "sv", "id": "sv", "title": "El Salvador", "name": "El Salvador" },
    { "code": "sy", "id": "sy", "title": "Syria", "name": "Syria" },
    { "code": "sz", "id": "sz", "title": "Swaziland", "name": "Swaziland" },
    { "code": "tc", "id": "tc", "title": "Turks and Caicos Islands", "name": "Turks and Caicos Islands" },
    { "code": "td", "id": "td", "title": "Chad", "name": "Chad" },
    { "code": "tf", "id": "tf", "title": "French Southern Territories", "name": "French Southern Territories" },
    { "code": "tg", "id": "tg", "title": "Togo", "name": "Togo" },
    { "code": "th", "id": "th", "title": "Thailand", "name": "Thailand" },
    { "code": "tj", "id": "tj", "title": "Tajikistan", "name": "Tajikistan" },
    { "code": "tk", "id": "tk", "title": "Tokelau", "name": "Tokelau" },
    { "code": "tl", "id": "tl", "title": "Timor-Leste", "name": "Timor-Leste" },
    { "code": "tm", "id": "tm", "title": "Turkmenistan", "name": "Turkmenistan" },
    { "code": "tn", "id": "tn", "title": "Tunisia", "name": "Tunisia" },
    { "code": "to", "id": "to", "title": "Tonga", "name": "Tonga" },
    { "code": "tp", "id": "tp", "title": "East Timor", "name": "East Timor" },
    { "code": "tr", "id": "tr", "title": "Turkey", "name": "Turkey" },
    { "code": "tt", "id": "tt", "title": "Trinidad and Tobago", "name": "Trinidad and Tobago" },
    { "code": "tv", "id": "tv", "title": "Tuvalu", "name": "Tuvalu" },
    { "code": "tw", "id": "tw", "title": "Taiwan", "name": "Taiwan" },
    { "code": "tz", "id": "tz", "title": "Tanzania", "name": "Tanzania" },
    { "code": "ua", "id": "ua", "title": "Ukraine", "name": "Ukraine" },
    { "code": "ug", "id": "ug", "title": "Uganda", "name": "Uganda" },
    { "code": "uk", "id": "uk", "title": "United Kingdom", "name": "United Kingdom" },
    { "code": "um", "id": "um", "title": "United States Minor Outlying Islands", "name": "United States Minor Outlying Islands" },
    { "code": "us", "id": "us", "title": "United States", "name": "United States" },
    { "code": "uy", "id": "uy", "title": "Uruguay", "name": "Uruguay" },
    { "code": "uz", "id": "uz", "title": "Uzbekistan", "name": "Uzbekistan" },
    { "code": "va", "id": "va", "title": "Vatican City State (Holy See)", "name": "Vatican City State (Holy See)" },
    { "code": "vc", "id": "vc", "title": "Saint Vincent and the Grenadines", "name": "Saint Vincent and the Grenadines" },
    { "code": "ve", "id": "ve", "title": "Venezuela", "name": "Venezuela" },
    { "code": "vg", "id": "vg", "title": "Virgin Islands (British)", "name": "Virgin Islands (British)" },
    { "code": "vi", "id": "vi", "title": "Virgin Islands (U.S.)", "name": "Virgin Islands (U.S.)" },
    { "code": "vn", "id": "vn", "title": "Viet Nam", "name": "Viet Nam" },
    { "code": "vu", "id": "vu", "title": "Vanuatu", "name": "Vanuatu" },
    { "code": "wf", "id": "wf", "title": "Wallis and Futuna", "name": "Wallis and Futuna" },
    { "code": "ws", "id": "ws", "title": "Samoa", "name": "Samoa" },
    { "code": "ye", "id": "ye", "title": "Yemen", "name": "Yemen" },
    { "code": "yt", "id": "yt", "title": "Mayotte", "name": "Mayotte" },
    { "code": "yu", "id": "yu", "title": "Yugoslavia (former)", "name": "Yugoslavia (former)" },
    { "code": "za", "id": "za", "title": "South Africa", "name": "South Africa" },
    { "code": "zm", "id": "zm", "title": "Zambia", "name": "Zambia" },
    { "code": "zr", "id": "zr", "title": "Zaire (former)", "name": "Zaire (former)" },
    { "code": "zw", "id": "zw", "title": "Zimbabwe", "name": "Zimbabwe" }
]